import FlexContainer from "@/components/atomic/FlexContainer";
import FlexRowContainer from "@/components/atomic/FlexRowContainer";
import Svg from "@/components/atomic/Svg";
import Text from "@/components/atomic/Text";
import contributors from "@/assets/contributors";
import Boundary from "@/components/atomic/Boundary";
import List from "@/components/atomic/List";
import ImageButton from "@/components/atomic/ImageButton";9

function Aside() {
  return (
    <FlexContainer rowPadding={10}>
      <FlexRowContainer
        tag="aside"
        gap={0}
        maxWidth={256}
      >
        <FlexRowContainer
          className="aside-about"
          gap={10}
          hasBottom
          columnPadding={10}
        >
          <Text
            fontSize="px16"
            color="black"
            isBold
            text="About"
          />
          <Text
            fontSize="px16"
            color="black"
            text="Bootstrap components built with React"
          />
          <FlexContainer
            justifyContents="flex_start"
            gap={4}
          >
            <Svg
              icon='link'
              color='black'
            />
            <Text
              fontSize="px14"
              color="blue_300"
              isBold
              text="react-bootstrap.github.io/"
              link="react-bootstrap.github.io/"
            />
          </FlexContainer>
          <FlexContainer>
            <List>
              {[
                <Boundary
                  backgroundColor="blue_100"
                >
                  <Text
                    fontSize="px12"
                    color="blue_300"
                    text="react"
                  />
                </Boundary>,
                <Boundary
                  backgroundColor="blue_100"
                >
                  <Text
                    fontSize="px12"
                    color="blue_300"
                    text="javascript"
                  />
                </Boundary>,
                <Boundary
                  backgroundColor="blue_100"
                >
                  <Text
                    fontSize="px12"
                    color="blue_300"
                    text="bootstrap"
                  />
                </Boundary>,
                <Boundary
                  backgroundColor="blue_100"
                >
                  <Text
                    fontSize="px12"
                    color="blue_300"
                    text="typescript"
                  />
                </Boundary>,
                <Boundary
                  backgroundColor="blue_100"
                >
                  <Text
                    fontSize="px12"
                    color="blue_300"
                    text="react-components"
                  />
                </Boundary>,
                <Boundary
                  backgroundColor="blue_100"
                >
                  <Text
                    fontSize="px12"
                    color="blue_300"
                    text="hacktoberfest"
                  />
                </Boundary>,
              ]}
            </List>
          </FlexContainer>
          <FlexRowContainer>
            <FlexContainer
              justifyContents="flex_start"
              gap={4}
            >
              <Svg
                icon='book'
                color="gray_400"
              />
              <Text
                color="gray_400"
                text="Readme"
                link="https://github.com/react-bootstrap/react-bootstrap#readme-ov-file"
              />
            </FlexContainer>
            <FlexContainer
              justifyContents="flex_start"
              gap={4}
            >
              <Svg
                icon='license'
                color="gray_400"
              />
              <Text
                color="gray_400"
                text="MIT License"
                link="https://github.com/react-bootstrap/react-bootstrap#MIT-1-ov-file"
              />
            </FlexContainer>
            <FlexContainer
              justifyContents="flex_start"
              gap={4}
            >
              <Svg
                icon='activity'
                color="gray_400"
              />
              <Text
                color="gray_400"
                text="Activity"
                link="https://github.com/react-bootstrap/react-bootstrap/activity"
              />
            </FlexContainer>
            <FlexContainer
              justifyContents="flex_start"
              gap={4}
            >
              <Svg
                icon='dialogue'
                color="gray_400"
              />
              <Text
                color="gray_400"
                text="Custom Properties"
                link="https://github.com/react-bootstrap/react-bootstrap/custom-properties"
              />
            </FlexContainer>
            <FlexContainer
              justifyContents="flex_start"
              gap={4}
            >
              <Svg
                icon='star'
                color="gray_400"
              />
              <Text
                color="gray_400"
                isBold
                text="22.3k"
              />
              <Text
                color="gray_400"
                text="stars"
                link="https://github.com/react-bootstrap/react-bootstrap/stargazers"
              />
            </FlexContainer>
            <FlexContainer
              justifyContents="flex_start"
              gap={4}
            >
              <Svg
                icon='watch'
                color="gray_400"
              />
              <Text
                color="gray_400"
                isBold
                text="422"
              />
              <Text
                color="gray_400"
                text="watching"
                link="https://github.com/react-bootstrap/react-bootstrap/watchers"
              />
            </FlexContainer>
            <FlexContainer
              justifyContents="flex_start"
              gap={4}
            >
              <Svg
                icon='fork'
                color="gray_400"
              />
              <Text
                color="gray_400"
                isBold
                text="3.6k"
              />
              <Text
                color="gray_400"
                text="forks"
                link="https://github.com/react-bootstrap/react-bootstrap/forks"
              />
            </FlexContainer>
            <Text
              color="gray_400"
              text="Report Repository"
              link="https://github.com/contact/report-content?content_url=https%3A%2F%2Fgithub.com%2Freact-bootstrap%2Freact-bootstrap&report=react-bootstrap+%28user%29"
            />
          </FlexRowContainer>
        </FlexRowContainer>
        <FlexRowContainer
          className="aside-releases"
          hasBottom
          columnPadding={10}
        >
          <FlexContainer
            justifyContents="flex_start"
            gap={4}
          >
            <Text
              fontSize="px16"
              color="black"
              isBold
              text="Releases"
            />
            <Boundary>
              <Text
                fontSize="px12"
                text="63"
              />
            </Boundary>
          </FlexContainer>
          <FlexContainer
            justifyContents="flex_start"
            gap={4}
          >
            <Svg
              icon="tag"
              color="green_300"
            />
            <FlexRowContainer gap={0}>
              <FlexContainer justifyContents="flex_start" gap={4}>
                <Text
                  isBold
                  text="v2.10.4"
                />
                <Boundary
                  hasBorder
                  borderColor="green_300"
                  backgroundColor="white"
                >
                  <Text
                    fontSize="px12"
                    color="green_300"
                    text="Latest"
                  />
                </Boundary>
              </FlexContainer>
              <Text
                fontSize="px12"
                color="gray_400"
                text="on Jun 30"
              />
            </FlexRowContainer>
          </FlexContainer>
          <Text
            color="blue_300"
            text="+ 62 releases"
            link="https://github.com/react-bootstrap/react-bootstrap/releases"
          />
        </FlexRowContainer>
        <FlexRowContainer
          className="aside-packages"
          hasBottom
          columnPadding={10}
        >
          <Text
            fontSize="px16"
            isBold
            text="Packages"
          />
          <Text
            fontSize="px12"
            color="gray_400"
            text="No packages published"
          />
        </FlexRowContainer>
        <FlexRowContainer
          className="aside-contributors"
          hasBottom
          columnPadding={10}
        >
          <FlexContainer
            justifyContents="flex_start"
            gap={4}
          >
            <Text
              fontSize="px16"
              color="black"
              isBold
              text="Contributors"
            />
            <Boundary>
              <Text
                fontSize="px12"
                text="475"
              />
            </Boundary>
          </FlexContainer>
          <List gap={3}>
            {[
              <ImageButton
                btnImg={contributors.ctrb_1}
                btnHandleClick={() => console.log('contributors icon clicked')}
              />,
              <ImageButton
                btnImg={contributors.ctrb_2}
                btnHandleClick={() => console.log('contributors icon clicked')}
              />,
              <ImageButton
                btnImg={contributors.ctrb_3}
                btnHandleClick={() => console.log('contributors icon clicked')}
              />,
              <ImageButton
                btnImg={contributors.ctrb_4}
                btnHandleClick={() => console.log('contributors icon clicked')}
              />,
              <ImageButton
                btnImg={contributors.ctrb_5}
                btnHandleClick={() => console.log('contributors icon clicked')}
              />,
              <ImageButton
                btnImg={contributors.ctrb_6}
                btnHandleClick={() => console.log('contributors icon clicked')}
              />,
              <ImageButton
                btnImg={contributors.ctrb_7}
                btnHandleClick={() => console.log('contributors icon clicked')}
              />,
              <ImageButton
                btnImg={contributors.ctrb_8}
                btnHandleClick={() => console.log('contributors icon clicked')}
              />,
              <ImageButton
                btnImg={contributors.ctrb_9}
                btnHandleClick={() => console.log('contributors icon clicked')}
              />,
              <ImageButton
                btnImg={contributors.ctrb_10}
                btnHandleClick={() => console.log('contributors icon clicked')}
              />,
              <ImageButton
                btnImg={contributors.ctrb_11}
                btnHandleClick={() => console.log('contributors icon clicked')}
              />,
              <ImageButton
                btnImg={contributors.ctrb_12}
                btnHandleClick={() => console.log('contributors icon clicked')}
              />,
              <ImageButton
                btnImg={contributors.ctrb_13}
                btnHandleClick={() => console.log('contributors icon clicked')}
              />,
              <ImageButton
                btnImg={contributors.ctrb_14}
                btnHandleClick={() => console.log('contributors icon clicked')}
              />,
            ]}
          </List>
          <Text
            color="blue_300"
            text="+ 461 contributors"
            link="https://github.com/react-bootstrap/react-bootstrap/graphs/contributors"
          />
        </FlexRowContainer>
        <FlexRowContainer
          className="aside-deployments"
          hasBottom
          columnPadding={10}
        >
          <FlexContainer
            justifyContents="flex_start"
            gap={4}
          >
            <Text
              fontSize="px16"
              color="black"
              isBold
              text="Deployments"
            />
            <Boundary>
              <Text
                fontSize="px12"
                text="2"
              />
            </Boundary>
          </FlexContainer>
          <FlexContainer
            justifyContents="flex_start"
            gap={4}
          >
            <Svg
              icon='success_background'
              color="green_300"
            />
            <Text
              color="black"
              isBold
              text="github-pages"
            />
            <Text
              fontSize="px12"
              color="gray_400"
              text="last year"
            />
          </FlexContainer>
        </FlexRowContainer>
        <FlexRowContainer className="aside-languages" columnPadding={10}>
          <Text
            fontSize="px16"
            color="black"
            isBold
            text="Languages"
          />
          <List>
            {[
              <FlexContainer
                gap={8}
              >
                <FlexContainer
                  gap={4}
                >
                  <Text
                    fontSize="px12"
                    isBold
                    text="TypeScript"
                  />
                  <Text
                    fontSize="px12"
                    text="65.3%"
                  />
                </FlexContainer>
              </FlexContainer>,
              <FlexContainer
                gap={8}
              >
                <FlexContainer
                  gap={4}
                >
                  <Text
                    fontSize="px12"
                    isBold
                    text="JavaScript"
                  />
                  <Text
                    fontSize="px12"
                    text="22.0%"
                  />
                </FlexContainer>
              </FlexContainer>,
              <FlexContainer
                gap={8}
              >
                <FlexContainer
                  gap={4}
                >
                  <Text
                    fontSize="px12"
                    isBold
                    text="MDX"
                  />
                  <Text
                    fontSize="px12"
                    text="11.8%"
                  />
                </FlexContainer>
              </FlexContainer>,
              <FlexContainer
                gap={8}
              >
                <FlexContainer
                  gap={4}
                >
                  <Text
                    fontSize="px12"
                    isBold
                    text="Other"
                  />
                  <Text
                    fontSize="px12"
                    text="0.9%"
                  />
                </FlexContainer>
              </FlexContainer>,
            ]}
          </List>
        </FlexRowContainer>
      </FlexRowContainer>
    </FlexContainer>
  );
};

export default Aside;